networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki

#  promtail:
#    image: grafana/promtail:2.9.2
#    ports:
#      - "3101:3101"
#    volumes:
#      - ./promtail.yml:/etc/promtail/promtail.yml
#    command: -config.file=/etc/promtail/promtail.yml
#    networks:
#      - loki
